name: maskify  
channels:
  - defaults
  - conda-forge  
  - pytorch
dependencies:
  - python=3.9
  - pytorch==1.11.0
  - torchvision==0.12.0
  - opencv
  - numpy
  - pillow  
  - plotly
  - pip
  - pip:
      - git+https://github.com/huggingface/transformers
      - requests
      - pandas
      - matplotlib